name: Integration tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: "localhost:5000"
      REGISTRY: "localhost:5000"
      DOCKER_BUILDKIT: "0"
    strategy:
      fail-fast: false
      matrix:
        make-target:
          - integration-test-layers
          - integration-test-misc
          - integration-test-run
          - k8s-executor-build-push integration-test-k8s

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-android: "true"
          remove-dotnet: "true"
          remove-haskell: "true"
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.22"
      - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v1

      - run: make install-container-diff k3s-setup
      - run: make ${{ matrix.make-target }}
